### PR TITLE
Test moralis connection

### PR DESCRIPTION
**Pull request by jaythebeez**

### CODE REVIEW

**Comment by jaythebeez** [comment]
I created this PR for us to test whether we will still get the issues we were getting with the former PR raised by @aman-webdev this PR is to solve issue 48.

**Comment by aman-webdev** [comment]
Authentication is working, we now just need to add info to the database...

**Comment by aman-webdev** [comment]
@jaythebeez the app is crashing 
image

**Comment by jaythebeez** [comment]
Error has been fixed

**Comment by aman-webdev** [comment]
image
@jaythebeez

**Comment by aman-webdev** [comment]
@jaythebeez this should not come everytime 
image
It should only ask info only the first time if the user isnt signed up yet

**Comment by jaythebeez** [comment]
Clear your local storage and test the app again enter your details again i deleted all users from the database

**Comment by aman-webdev** [comment]
@jaythebeez I am still getting this 
image

**Comment by aman-webdev** [comment]
When creating invoice 
image

**Comment by aman-webdev** [comment]
and if i refresh this still pops up even tho i have entered this info earlier 
image

**Comment by jaythebeez** [comment]
Try clearing session storage and cookies also while i check on the error from my side

**Comment by aman-webdev** [comment]
I did clear storage

**Review by aman-webdev — CHANGES_REQUESTED** [review]
image

issue for creating invoice

**Pull request closed without merging**
